# Generated by Django 2.2.7 on 2019-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Logo', 'LOGO'), ('Icon', 'ICON'), ('Poster', 'POSTER'), ('Website', 'WEBSITE')], default='Logo', max_length=120),
        ),
    ]
