# Generated by Django 2.2.7 on 2019-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_stage',
            field=models.CharField(choices=[('1', 'Design requested'), ('2', 'Design pending approval'), ('3', 'Design approved')], default='1', max_length=120),
        ),
    ]
