# Generated by Django 2.2.7 on 2019-12-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191218_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_stage',
            field=models.CharField(choices=[('Design requested', 'Design requested'), ('Design pending approval', 'Design pending approval'), ('Change/s requested', 'Change/s requested'), ('Design approved', 'Design approved')], default='Design requested', max_length=120),
        ),
    ]
