# Generated by Django 2.2.7 on 2020-01-10 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191218_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.FileField(upload_to='designs')),
                ('preview_image', models.ImageField(upload_to='preview_images')),
                ('customer', models.CharField(max_length=120)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_stage', models.CharField(choices=[('Design requested', 'Design requested'), ('Design pending approval', 'Design pending approval'), ('Change/s requested', 'Change/s requested'), ('Design approved', 'Design approved')], default='Design pending approval', max_length=120)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
