# Generated by Django 2.2.7 on 2020-01-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_revisions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revisions',
            new_name='Revision',
        ),
    ]
