# Generated by Django 2.2.7 on 2020-01-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200111_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='design_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Design'),
        ),
    ]
