# Generated by Django 2.2.7 on 2020-01-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200112_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='type',
        ),
    ]
