# Generated by Django 2.2.7 on 2020-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_revision_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_stage',
        ),
        migrations.AlterField(
            model_name='design',
            name='order_stage',
            field=models.CharField(choices=[('Design pending approval', 'Design pending approval'), ('Design accepted', 'Design accepted'), ('Design rejected', 'Design rejected')], default='Design pending approval', max_length=120),
        ),
    ]
