# Generated by Django 2.2.7 on 2020-01-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200113_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
