# Generated by Django 2.2.7 on 2020-01-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
