# Generated by Django 2.2.7 on 2020-01-15 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_design_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=120)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('testimonial_text', models.TextField()),
                ('design_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Design')),
            ],
        ),
    ]
