# Generated by Django 2.2.7 on 2020-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200130_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Logo', 'Logo'), ('Icon', 'Icon'), ('Avatar', 'Avatar'), ('Illustration', 'Illustration')], default='Logo', max_length=120),
        ),
    ]
