# Generated by Django 2.2.7 on 2020-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200131_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.FileField(blank=True, default='image.png', upload_to='references'),
            preserve_default=False,
        ),
    ]
