# Generated by Django 2.2.7 on 2020-01-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200131_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='design_id',
            new_name='design_number',
        ),
    ]
