# Generated by Django 2.2.7 on 2020-01-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200131_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='customer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='customer',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='customer',
            new_name='author',
        ),
    ]
