# Generated by Django 2.2.7 on 2019-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('town_or_city', models.CharField(blank=True, max_length=40)),
                ('street_address1', models.CharField(blank=True, max_length=40)),
                ('street_address2', models.CharField(blank=True, max_length=40)),
                ('county', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField()),
            ],
        ),
    ]
